# Generated by Django 4.2.25 on 2025-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('country', models.CharField(default='IN', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
